# Generated by Django 3.2.12 on 2022-06-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imageName',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='画像名'),
        ),
        migrations.AddField(
            model_name='profile',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='S3内の画像保存先URL'),
        ),
    ]
