# Generated by Django 3.2.12 on 2022-06-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220606_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='S3内の画像保存先URL'),
        ),
    ]
