# Generated by Django 3.2.12 on 2022-06-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='image_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='S3内の画像保存キー'),
        ),
    ]
