version: "3"

services:
  db:
    container_name: dev_db
    build:
      context: . # /poppie ディレクトリにてdockerfile内のステップを実行する
      dockerfile: ./docker/db/Dockerfile.dev-test
    image: poppie:postgres
    ports:
      - "5432:5432"
    volumes:
      - dev_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      # DjangoでPostgresを使う場合、タイムゾーンの環境変数を指定しておかないと、__rangeでクエリを投げた時、デフォルトのUTCでデータを取得してしまう
      - TZ=Asia/Tokyo
    # env_file: .docker_env

  # TODO: djangoでmailcatcherを使えるようにする
  # mail:
  #   image: helder/mailcatcher
  #   ports:
  #     - "1026:25"
  #     - "1081:80"


volumes:
  dev_db_data:
