# Generated by Django 3.2.12 on 2022-05-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="point",
            field=models.IntegerField(default=0, verbose_name="会社が配布可能なポイント"),
        ),
    ]
