# Generated by Django 3.2.12 on 2022-06-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Private')], default=0, verbose_name='ステータス'),
        ),
    ]
