# Generated by Django 3.2.12 on 2022-06-05 08:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_item_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExchangedItem',
            new_name='OwnItem',
        ),
        migrations.RenameField(
            model_name='exchangeditemlog',
            old_name='exchanged_item',
            new_name='own_item',
        ),
        migrations.AlterModelTable(
            name='ownitem',
            table='own_item',
        ),
    ]
