# Generated by Django 3.2.12 on 2022-06-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220605_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='S3内の画像保存キー'),
        ),
    ]
