# Generated by Django 3.2.12 on 2022-06-07 09:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20220607_1614'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OwnItem',
            new_name='ExchangeAppliedItem',
        ),
        migrations.RenameField(
            model_name='exchangeditemlog',
            old_name='own_item',
            new_name='exchange_applied_item',
        ),
        migrations.AlterModelTable(
            name='exchangeapplieditem',
            table='exchange_applied_items',
        ),
        migrations.AlterModelTable(
            name='exchangeditemlog',
            table='exchanged_item_logs',
        ),
    ]
