name: e2e CI

on:
  # push: push したら jobs を実行する。
  # workflow_dispatch: github で手動で実行可能にする。(テストを実行するのに、プッシュやプルリクを送りたくない場合に記述しておくと良い)
  push:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  test_e2e:
    runs-on: ubuntu-latest
    env:
      ENV_NAME: ${{secrets.ENV_NAME}}
      SECRET_KEY: ${{secrets.SECRET_KEY}}
      ENGINE: ${{secrets.ENGINE}}
      POSTGRES_DB: ${{secrets.POSTGRES_DB}}
      POSTGRES_USER: ${{secrets.POSTGRES_USER}}
      POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
      HOST: ${{secrets.HOST}}
      PORT: ${{secrets.PORT}}
      AWS_S3_ACCESS_KEY_ID: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
      AWS_S3_SECRET_ACCESS_KEY: ${{secrets.AWS_S3_SECRET_ACCESS_KEY}}
      AWS_STORAGE_BUCKET_NAME: ${{secrets.AWS_STORAGE_BUCKET_NAME}}
      AWS_REGION_NAME: ${{secrets.AWS_REGION_NAME}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: "14.17.5"
      - name: Cache yarn
        uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/frontend/node_modules
            ${{ github.workspace }}/frontend/.next/cache
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
            ${{ runner.os }}-
      - name: Install Dependencies
        working-directory: ./frontend
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Run Next.js Build
        working-directory: ./frontend
        run: |
          yarn make-e2e-env
          yarn build
      - name: Set up docker
        run: docker-compose -f ./docker/e2e/docker-compose-e2e.yml up --build -d


      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        # withでは、アクションで定義される入力パラメータを設定できます。
        with:
          python-version: 3.9
      # Djangoの環境をインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/base.txt
          pip install -r requirements/test.txt
          pip install pytest-django
      - name: Run migrations and seed
        run: ./seed.sh
      - name: Run Django
        # バックグランド実行
        # https://stackoverflow.com/questions/66877730/how-to-use-django-selenium-testing-in-github-actions
        run: python manage.py runserver &


      # - name: Run e2e test
      #   id: e2e_test
      #   run: |
      #     cd ./frontend
      #     yarn cy:run


      # Next.jsアプリを起動(バックグラウンド実行)
      - name: Start App
        run: yarn start &
      # Cypress実行
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          # Cypress を ./frontend/ に配置しているため、working-directoryを指定(デフォルトはルートディレクトリ)
          working-directory: frontend
      # Cypress実行時に生成されたビデオとスクリーンショットを保存
      - name: Save e2e screenshots at failure
        uses: actions/upload-artifact@v3
        with:
          name: e2e-test-logs
          path: |
            ${{ github.workspace }}/frontend/cypress/screenshots/
            ${{ github.workspace }}/frontend/cypress/videos/
          retention-days: 1
        if: failure() && steps.e2e_test.outcome == 'failure'
